style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kc-workspace/kcs
options:
  commits:
    filters:
      Type:
        - feat
        - perf
        - fix
        - chore
  commit_groups:
    sort_by: Custom
    title_order:
        - feat
        - perf
        - fix
        - chore
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      chore: Chore
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
