name: Pull request

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Testing
        run: ./tests/start.sh
      - name: Saving result
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
            ./tests/.results
